[package]
name = "demiurge"
version = "0.1.0"
edition = "2021"
authors = ["Robert Fogarty <rgaf@purgator.io>"]

[dependencies]
itertools = "0.10"
rand = "0.8"
rand_chacha = "0.3"
rand_distr = "0.4"
twox-hash = "1.6"

[dev-dependencies]
image = "0.23"
minifb = "0.20"
